name: orc
version: 0.5.9
description: A receptionist web-app.
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  intl: any
  logging: any
  markdown: any
  okeyee:
    path: ../../okeyee
  orf:
    path: ../framework
    version: '>=0.0.31'
