name: orc
version: 0.5.9
description: A receptionist web-app.
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  intl: any
  logging: any
  markdown: any
  okeyee2:
    path: ../../okeyee
  orf:
    path: ../framework
    version: '>=0.0.30'
  testapi:
    path: ../../dart_api

dev_dependencies:
    build_runner: any
    build_test: any
    build_web_compilers: any
    test: any
