name: ors
version: 0.3.0+rc-1
description: Server stack for the OpenReception application.
environment:
  sdk: '>=1.0.0 <3.0.0'
dependencies:
  args: any
  xml: any
  crypto: any
  emailer:
    git:
      ref: dart-2.0
      url: https://github.com/rostgaard/emailer.git
  esl: '>=0.0.17 <1.0.0'
  http: any
  intl: any
  logging: any
  oauth2: any
  orf:
    path: ../framework
    version: '>=0.0.30'
  #route: any
  web_socket_channel: any
  shelf: any
  shelf_cors:
    path: /home/krs/Projects/dart-shelf_cors
    version: any
  shelf_route:
    path: ../../shelf_route
  shelf_web_socket: any
