name: ors
version: 0.2.0+rc-1
description: Server stack for the OpenReception application.

environment:
  sdk: ">=1.0.0 <3.0.0"

dependencies:
  args: any
  xml: any
  crypto: any
  emailer:
    git:
      ref: dart-2.0
      url: https://github.com/rostgaard/emailer.git
  shelf_cors:
    git:
      ref: master
      url: https://github.com/rostgaard/dart-shelf_cors.git

  esl: ^0.1.0
  http: any
  intl: any
  logging: '>= 0.11.0 < 1.0.0'
  oauth2: any
  orf:
    path: ../framework
  web_socket_channel: any

dev_dependencies:
  shelf_router: any
  test: any
  pedantic: ^1.0.0
