api:
	java -cp openapi-generator-cli-4.2.3.jar:openapi-dart-generator-2.4.jar org.openapitools.codegen.OpenAPIGenerator generate -i api.yml --additional-properties pubName=or_api -g dart --enable-post-process-file
