name: orf
version: 0.0.31+0
author: BitStackers
description: A utility package for the OpenReception application that provides data model service and storage layer.
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  archive: any
  intl: any
  logging: any
dev_dependencies:
  http: any
  path: any
  test: any
  xml: any
