name: ort
version: 0.3.0
description: OpenReception Acceptance and integration tests
dependencies:
  http: any
  logging: any
  esl:
    path: ../../libesl-dart
  orf:
    path: ../framework
  phonio:
    git:
      ref: dart-2.0
      url: https://github.com/rostgaard/Phonio.git
dev_dependencies:
  test: any
